version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Simha
      MYSQL_DATABASE: django_crud
    volumes:
      - ./db/mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - my_networks

  backend:
    build: ./Django_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=django_crud
      - DB_USER=root
      - DB_PASSWORD=Simha
    networks:
      - my_networks

networks:
 my_networks:
   driver: bridge